# Generated by Django 4.2.3 on 2023-07-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='users/img_perfiles/batman.jpg', upload_to='users/img_perfiles'),
        ),
    ]
